<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="felix.20201206020149.2"><vh>Introduction</vh></v>
</vnodes>
<tnodes>
<t tx="felix.20201206020149.2">morejs is an outliner vscode extension

For now, examples and jsonOutline.ts kept for demo purposes.

</t>
</tnodes>
</leo_file>
